os: linux
dist: bionic
language: java

notifications:
  email: false

### Maven basic build ###
jobs:
  include:
    # 1. Test
    - stage: Test
    - jdk: openjdk11

cache:
  directories:
    - ~/.m2/repository